### ISSUE TITLE
Do we need function filter support?

### ISSUE THREAD

**Issue by b1tg** [hasherezade/tiny_tracer#33]
Currently Tiny Tracer don't allow to filter what function to log, how do you think about this function? 

We may need a seperated config file or put them in params.txt , something like:

```
Kernel32;LoadLibraryW;1
kernel32;LoadLibraryA;1
# KERNEL32;GetProcAddress <- do not log GetProcAddress 
# CreateEvent* <- pattern match
```

**Comment by hasherezade** [comment]
@b1tg - it's a good idea to have such filtering. I will add it soon. (Although I don't think params.txt is a good place to put this list - I will rather do it as a separate file).

**Comment by hasherezade** [comment]
@b1tg  - I added filtering, check it out.
Now you can define a list of your excluded functions in [excluded.txt](https://github.com/hasherezade/tiny_tracer/blob/master/install32_64/excluded.txt)
No pattern matching for now, only explicit names.
Please let me know what do you think.

**Comment by b1tg** [comment]
Cool, I would test it after I fix my dev enviroment, currently I failed to build the latest master(18807e6b14709c8768110deb5e96f8695a4d893b) and 31e29a9ea72df8844df6d8bd4903678ca8021154, seems win_hdrs_init.bat failed because my windows kit is under D:/

**Comment by b1tg** [comment]
Windows Kit folder can be located use:
```
C:\>reg query "HKLM\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0" /v InstallationFolder

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0
    InstallationFolder    REG_SZ    D:\Windows Kits\10\
```

**Comment by b1tg** [comment]
This commit fixes my problem, and the filtering feature is working fine for me, very helpful, thanks.

**Comment by hasherezade** [comment]
Cool, thanks for checking it!
