### ISSUE TITLE
You'll need a new app to open this .exe file

### ISSUE THREAD

**Issue by ELJoOker2004** [hasherezade/tiny_tracer#54]
i know this problem was discussed before , but i tried the solutions provided and it didn't fix the problem. 
KDB check output is : KDB: Disabled
AV is disabled 
running using run me bat gives 
`run_me.bat "C:\Users\ELJoOker\Downloads\you_bee_ex (1).exe" exe
PIN is trying to run the app:
"C:\Users\ELJoOker\Downloads\you_bee_ex (1).exe"
The system cannot find the path specified.
Target module: "C:\Users\ELJoOker\Downloads\you_bee_ex (1).exe"
Tag file: "C:\Users\ELJoOker\Downloads\you_bee_ex (1).exe.tag"
E: [tid:26508] Invalid tool DLL name :  C:\pin\source\tools\tiny_tracer\install32_64\TinyTracer32.dll
Press any key to continue . . .`
pin file is in default location `C:\\pin`  and compiled using VS 2022 using Pin 3.30

**Comment by hasherezade** [comment]
Hi @ELJoOker2004 
Do you have the compiled TinyTracer DLL exactly at this path? 
```
C:\pin\source\tools\tiny_tracer\install32_64\TinyTracer32.dll
```
Are you sure the DLL is valid and not corrupt?
Few more questions:
+ Is your application that you are trying to run 32 or 64 bit?
+ Is it a .NET application?

Also, the .bat says that the given path is invalid:
```
PIN is trying to run the app: "C:\Users\ELJoOker\Downloads\you_bee_ex (1).exe" The system cannot find the path specified. 
```
Not sure what path it cannot find, but can you try to rename your exe to something simple, like `test123.exe` and try again?
How exactly you are trying to run your app? Via context menu, or in some other way? Can you send me the screenshots of your installation directory tree?

**Comment by ELJoOker2004** [comment]
ok now i know the problem tysm , 
it was that the path was 
```shell
C:\pin\source\tools\tiny_tracer-2.7.1\install32_64\TinyTracer32.dll
``` 
instead of 
```shell
C:\pin\source\tools\tiny_tracer\install32_64\TinyTracer32.dll
``` 
sorry for bothering and thanks for your help , hava a great day <3
