### ISSUE TITLE
How to debug the dll module of tiny trace?

### ISSUE THREAD

**Issue by x64bugreport** [hasherezade/tiny_tracer#58]
I tried delaying using the following command:-pause_tool 20,But when I attached to the target process, vs2022 broke at a strange breakpoint. I continued running F5 and the target program exited. VS2022 also exited the attached state. How can I debug the tiny trace module? Thank you!
When this prompt appears, continue F5 and the target program will exit without interrupting the function in the tiny trace module.
![11111111111](https://github.com/hasherezade/tiny_tracer/assets/34920463/43eb87e4-b69b-4915-93a4-c83447487635)

**Comment by x64bugreport** [comment]
I USE PIN 3.30 
VS2022
WIN10 22H2

**Comment by x64bugreport** [comment]
Please tell me how you debug when developing tiny trace? Thank you very much!

**Comment by x64bugreport** [comment]
I also tried using vs extension to debug
https://software.intel.com/sites/landingpage/pintool/docs/98579/Pin/doc/html/index.html -> Advanced Debugging Extensions on Windows
Unfortunately, there is no Pin Debugger in the debugging options of vs2022.
![1111](https://github.com/hasherezade/tiny_tracer/assets/34920463/03d25599-cfd7-47b0-b3c5-15162301943f)
I tried to use the TCP port to attach the target process, VS2022 crashed and exited, and the target program printed failure information.

**Comment by x64bugreport** [comment]
I searched for relevant information in a blog post, but he uses windbg, and it seems that it cannot be debugged using VS.

**Comment by hasherezade** [comment]
Hi @x64bugreport !
To be very honest, I never debugged it in Visual Studio. Pin Tools are hard to debug with external debuggers, so I just debug it by logs - I print debug messages in the strategic points, and verify my assumptions. Sure it is not as convenient as a proper debugging tool, but it is reliable. I will try to research more about how to debug it with external debuggers, and possibly add some information about it to the Tiny Tracer Wiki.

**Comment by x64bugreport** [comment]
> Hi @x64bugreport ! To be very honest, I never debugged it in Visual Studio. Pin Tools are hard to debug with external debuggers, so I just debug it by logs - I print debug messages in the strategic points, and verify my assumptions. Sure it is not as convenient as a proper debugging tool, but it is reliable. I will try to research more about how to debug it with external debuggers, and possibly add some information about it to the Tiny Tracer Wiki.

Thank you very much for your reply, and I look forward to your updating debugging related content in the wiki.

**Comment by hasherezade** [comment]
@x64bugreport - this is my note on debugging TinyTracer with Visual Studio: 
https://github.com/hasherezade/tiny_tracer/wiki/Debugging-TinyTracer#debugging-with-visual-studio
I hope it helps a bit. I will be improving it and adding illustrations.
