### ISSUE TITLE
Build Error on VS 2022: "CL.exe" exited with code -1073740791

### ISSUE THREAD

**Issue by WildByDesign** [hasherezade/tiny_tracer#59]
Visual Studio 2022 (17.10.3) 64-bit
Windows 11 24H2 (Build 26100.1000)
Platform tools: upgraded to v143
Windows SDK: 10.0.22621.0

I have tried every possible variation that I can think of, but cannot build tiny-tracer 32-bit or 64-bit binaries in Release or Debug.

Also, it fails with the same code with the current code (as of today) in master and also the 2.7.1 release sources.

Error: Error	`MSB6006	"CL.exe" exited with code -1073740791.	TinyTracer	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	755`

Thank you for your time.

**Comment by xorhex** [comment]
Visual Studio 2022 (17.10.3) 64-bit
Windows 10
Platform tools: upgraded to v143
Windows SDK: 10.0.22621.0

Same here: `1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6006: "CL.exe" exited with code -1073740791.`

**Comment by hasherezade** [comment]
hi! thank you for reporting, I will look into it

**Comment by hasherezade** [comment]
This is not something TinyTracer specific, I see the same problem occurs when trying to build `MyPinTool` from the original Pin package (using VS 2022):

![my_tool_err](https://github.com/hasherezade/tiny_tracer/assets/3115348/7bad14f5-7b22-482c-83d5-fd0e4055ce4e)

I had no problems building in VS 2019 though...
I will try to find out why it happens, and let you know.

**Comment by hasherezade** [comment]
I know it is annoying, so I came up with a workaround to this problem. From now, you can download the ready-made builds of TinyTracer from AppVeyor server!

Click the AppVeyor button on the README:
[![Build status](https://ci.appveyor.com/api/projects/status/543ql60gxxuri9j2?svg=true)](https://ci.appveyor.com/project/hasherezade/tiny-tracer)
 then select the plaftorm, and then go to the "Artifacts" tab.

**Comment by WildByDesign** [comment]
@hasherezade Thank you very much. I wasn't able to test it before and now I can. I appreciate it.

I'm not sure if the issue should be closed with this workaround or not. It's totally up to you.

**Comment by hasherezade** [comment]
@WildByDesign - the mentioned problem is still not solved, so I will keep the issue open. Not sure if I can fix it though, it should rather be fixed on the Pin side. The new Visual Studio seems to not like their header files.

**Comment by HongThatCong** [comment]
VS 2022 change a option in linker

**Comment by x64bugreport** [comment]
I know this question. Let me answer it by removing fp:strict from all command lines in the C++ option.

**Comment by hasherezade** [comment]
thank you @x64bugreport, it worked!
