### ISSUE TITLE
Cannot compile the project: Reference to std::size_t is ambiguous

### ISSUE THREAD

**Issue by acheron2302** [hasherezade/tiny_tracer#62]
Operating System: Windows 11 Pro version 23H2
Visual Studio version: 17.11.1 (2022)
MSVC version: 143
Windows SDK version: 10.0.22621
Visual studio can't compile the code, I have put it into pin/source/tools. There are 365 error but one of them is size_t is ambiguous.

I think the main reason is that it conflict with the pin predefined.
![image](https://github.com/user-attachments/assets/eee7557f-0155-449b-ab09-d49d91c27a44)

**Comment by hasherezade** [comment]
hi @acheron2302 !
Check out the changes in the new branch: https://github.com/hasherezade/tiny_tracer/tree/explicit_std and let me know if it is ok now.
Regarding:

> Visual studio can't compile the code, I have put it into pin/source/tools. 

This is normal and [documented](https://github.com/hasherezade/tiny_tracer/wiki/Installation#how-to-compile) behavior.

**Comment by acheron2302** [comment]
Thanks for your quick response, I have modified some other places to use std::size_t but after modify all of them, there are still error with std::setw
![image](https://github.com/user-attachments/assets/01f84097-de87-4f6a-bedf-4c3629b7a8bc)

**Comment by acheron2302** [comment]
ok update even after remove std::setw. I still get a lot of error, I think the reason because compiler get conflict with each other

**Comment by hasherezade** [comment]
@acheron2302  - I updated the branch and fixed the remaining `size_t` -> `std::size_t`.
Either way, what you are describing looks weird, I cannot reproduce this problem. You can see that I also use VS2022 on AppVeyor, and it builds without errors.
Maybe there is something wrong with your compiler settings?
Can you delete the full source, download the last supported PIN (this one: https://software.intel.com/sites/landingpage/pintool/downloads/pin-external-3.31-98861-g71afcc22f-msvc-windows.zip) , and try again, following exactly the steps that are described on Wiki?
https://github.com/hasherezade/tiny_tracer/wiki/Installation

**Comment by acheron2302** [comment]
Here is the log of the fail compile and the cl compile, most of the compile error is from the standard library so maybe the compiler is broken some where.
[TinyTracer.log](https://github.com/user-attachments/files/16715619/TinyTracer.log)

[CL.command.1.txt](https://github.com/user-attachments/files/16715628/CL.command.1.txt)

**Comment by hasherezade** [comment]
@acheron2302  - did you try to pull everything from scratch?

**Comment by acheron2302** [comment]
Oh thanks after I redownload it the code compile now didn't pull everything from scratch but just copy and paste the last time
