### ISSUE TITLE
Bug for Trap Flag simulation

### ISSUE THREAD

**Issue by Maladiy** [hasherezade/tiny_tracer#69]
When I added debugger and VM protection with vmprotect
![2024-12-17 211823](https://github.com/user-attachments/assets/02489256-16c1-4cdb-873c-bc34d3bb9af8)
and set EMULATE_SINGLE_STEP=True
```
ANTIDEBUG=1
ANTIVM=0
EMULATE_HYPERV=False
EMULATE_SINGLE_STEP=True
```
I found that a VM was detected.
![2024-12-17 211059](https://github.com/user-attachments/assets/56d05a67-096d-436e-937c-69c71c03f614)

It was strange because I was not running in a VM. To figure out why this happened, I looked at the leak source code of vmprotect and found a detection as shown below.  https://github.com/jmpoep/vmprotect-3.5.1/blob/master/runtime/loader.cc#L2514
![image](https://github.com/user-attachments/assets/ac13db2f-8c06-4a99-946b-d6bef14ba0e4)

This is a common VM detection. https://howtohypervise.blogspot.com/2019/01/a-common-missight-in-most-hypervisors.html
I wrote code to verify whether tiny_tracer passed this test. 

```
	uint8_t mem_val;
	__try 
	{
		// set T flag
		__writeeflags(__readeflags() | 0x100);
		__nop();
		__nop();
		
		printf("Debugger Found\n");
	}
	__except (mem_val = *static_cast<uint16_t*>((GetExceptionInformation())->ExceptionRecord->ExceptionAddress), EXCEPTION_EXECUTE_HANDLER) 
	{
		if (mem_val != 0x90)
		{
			printf("Virtual Machine Found\n");
			printf("mem_val:0x%x\n", mem_val);
		}
	}

	printf("Check done\n");
```
 Unfortunately tiny_tracer had an error when simulating the Trap Flag.
![image](https://github.com/user-attachments/assets/76c65284-fe52-4fac-8024-5f672feebb17)

**Comment by hasherezade** [comment]
Hi @Maladiy ! Thank you for your report. Please check the latest patch, it should help. 

![check1](https://github.com/user-attachments/assets/cb4fc4b8-6af7-49ee-b842-b251df30aa5b)

Let me know if everything is ok.

**Comment by Maladiy** [comment]
Thanks a lot. I tested tiny_tracer and it works well.
