### ISSUE TITLE
Build issue with Intel Pin 3.19 Windows

### ISSUE THREAD

**Issue by slpycatzz** [hasherezade/tiny_tracer#8]
Hi,

I would like to highlight a build issue with Intel Pin 3.19, Windows version. Though you have mentioned in the installation guide that it was tested against 3.16, I thought that it would be a good idea to let you know the build issue I faced for Intel Pin 3.19.

It seems that for Intel Pin 3.19, they have removed the ```pinvm.lib``` from ```%pin_root%\ia32\lib``` directory, resulting in a build error.

I have tested against version 3.16 to 3.18, and building is successful for all those versions in that range.

**Comment by hasherezade** [comment]
Hi! No worries, I will update to build it with the latest Pin soon.

**Comment by slpycatzz** [comment]
Awesome! Feel free to close the issue when it's ready. Thanks~

**Comment by slpycatzz** [comment]
I have verified that it works now with Intel Pin 3.19. Thanks for the fix! Closing the issue.
